# Generated by Django 5.0.6 on 2024-05-28 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='ranking_average',
        ),
    ]
