# Generated by Django 5.0.6 on 2024-05-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_restaurant_ranking_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='reservations',
            field=models.IntegerField(default=1),
        ),
    ]
