# Generated by Django 5.0.6 on 2024-05-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Restaurante', 'Restaurante'), ('Cliente', 'Cliente')], default='Cliente', max_length=11),
        ),
    ]
