# Generated by Django 5.0.6 on 2024-05-28 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_schedule_reservations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='reservations',
        ),
    ]
